print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "E:/Unity Projects/theBends_Project/Assets/Models/levelModularKit.ma"`)
{
	file -o "E:/Unity Projects/theBends_Project/Assets/Models/levelModularKit.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "E:/Unity Projects/theBends_Project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"E:\\Unity Projects\\theBends_Project\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "E:/Unity Projects/theBends_Project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
